version: '3'
services:
  jenkins-docker-slave:
    user: root
    build: .
    restart: unless-stopped
    ports:
      - "8180:8080"
    volumes:
      - ./jenkins-home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock