version: '3'
services:
  jenkins:
    user: root
    image: jenkins/jenkins:latest
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./jenkins-home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ./jenkins-docker-slave:/var/jenkins-docker-slave