version: '3'
services:
  portainer:
    image: portainer/portainer:latest
    build: .
    restart: unless-stopped
    ports:
      - "9001:9001"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
